package Entities;
// Generated Mar 27, 2018 8:11:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idclientes;
     private String name;
     private String surname;
     private String email;
     private String password;
     private Set cars = new HashSet(0);

    public Clientes() {
    }

    @Override
    public String toString() {
        return "Clientes{" + "name=" + name + ", surname=" + surname + ", email=" + email + '}';
    }

	
    public Clientes(String name, String surname, String email, String password) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.password = password;
    }
    public Clientes(String name, String surname, String email, String password, Set cars) {
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.password = password;
       this.cars = cars;
    }
   
    public Integer getIdclientes() {
        return this.idclientes;
    }
    
    public void setIdclientes(Integer idclientes) {
        this.idclientes = idclientes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCars() {
        return this.cars;
    }
    
    public void setCars(Set cars) {
        this.cars = cars;
    }




}


